#!/usr/bin/env bash

#
# Just get the config.xml file
#
# This check uses SSH but there are other methods:
#
# https://docs.netgate.com/pfsense/en/latest/backup/remote-config-backup.html
# https://www.proteansec.com/linux/pfsense-automatically-backup-configuration-files/
# https://fattylewis.com/2015/08/15/script-to-back-up-pfsense-config/
# 
#

    WARN_DAYS=60
         WARN=$(( WARN_DAYS * 24 * 60 * 60 ))

     EXCLUDES=()
   #EXCLUDES+=("00:E2:23:80:22:3B:C0:23:55:47:51:77:E9:26:93:62:AF:0C:56:F1")

      CA_HOST="server1.domain.local"
 CHECK_PREFIX="server1"

      COUNTER=0

for cert in $( ssh -o ConnectTimeOut=5 monitoring@${CA_HOST} cat "/conf/config.xml" | xmlstarlet sel -t -m "//*/crt" -v . -n ); do

         DATA=$( echo "$cert" | base64 -d )
  FINGERPRINT=$( echo "$DATA" | openssl x509 -noout -fingerprint | sed 's/SHA1 Fingerprint=//' )

  if [[ " ${EXCLUDES[@]} " =~ " ${FINGERPRINT} " ]]; then
    continue
  fi

  (( COUNTER++ ))

        SUBJECT=$( echo "$DATA" | openssl x509 -noout -subject   | sed 's/subject=//'   )
     START_DATE=$( echo "$DATA" | openssl x509 -noout -startdate | sed 's/notBefore=//' )
       END_DATE=$( echo "$DATA" | openssl x509 -noout -enddate   | sed 's/notAfter=//'  )
  END_DATE_UNIX=$( date -d "$END_DATE" +%s )
            NOW=$( date +%s )

   VALID_WINDOW=$(( ( END_DATE_UNIX - NOW ) / 60 / 60 / 24 ))

  if [[ ${VALID_WINDOW} -lt 0 ]]; then

    VALID=0

  else

    VALID=${VALID_WINDOW}

  fi

  if [[ ${END_DATE_UNIX} -lt ${NOW} ]]; then

    printf "2 CERT_%s_%03i valid_days=%s %s | %s | %s\n" "${CHECK_PREFIX}" "$COUNTER" "$VALID" "$SUBJECT" "NotValidBefore: $START_DATE" "NotValidAfter: $END_DATE"

  elif [[ $(( END_DATE_UNIX - WARN )) -lt ${NOW} ]]; then

    printf "1 CERT_%s_%03i valid_days=%s %s | %s | %s\n" "${CHECK_PREFIX}" "$COUNTER" "$VALID" "$SUBJECT" "NotValidBefore: $START_DATE" "NotValidAfter: $END_DATE"

  else

    printf "0 CERT_%s_%03i valid_days=%s %s | %s | %s\n" "${CHECK_PREFIX}" "$COUNTER" "$VALID" "$SUBJECT" "NotValidBefore: $START_DATE" "NotValidAfter: $END_DATE"

  fi

done
